spring:
  application:
    name: notification-service

  kafka:
    topic-name: email-send-topic

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}  #your email
    password: ${MAIL_PASSWORD:}  #your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}