server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SERVICE_NAME}
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comment-service/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/post-service/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user-service/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${JWT_ISSUER_HOST:localhost}:8080/realms/blog-app-realm
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
              - roles
        provider:
          keycloak:
            issuer-uri: http://${JWT_ISSUER_HOST:localhost}:8080/realms/blog-app-realm
            user-name-attribute: preferred_username


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URI:localhost}:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG