spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${JWT_ISSUER_HOST:localhost}:8080/realms/blog-app-realm

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URI:localhost}:8761/eureka
  instance:
    preferIpAddress: true

loki:
  host: http://${LOKI_HOST:localhost}:3100/loki/api/v1/push
