server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/blog-user-service
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${JWT_ISSUER_HOST:localhost}:8080/realms/blog-app-realm

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

keycloak:
  realm: blog-app-realm
  auth-server-url: http://${JWT_ISSUER_HOST:localhost}:8080
  client-id: ${CLIENT_ID:blog-gateway-client}
  client-secret: ${CLIENT_SECRET:qFhGH5UEzXxlJDVDDdKmXbMSSTL7yvYy}
  username: admin
  password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URI:localhost}:8761/eureka
  instance:
    preferIpAddress: true
logging:
  level:
    org.springframework.security: DEBUG
